version: '3.4'
services:
  postgres:
    image: postgres:9.6.9-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fhir
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=leaving-grants-groups-ratio-colombia-ieee-firing-appears-finding-listings-fixed-dramatic
  fhir-api:
    image: ibrohim/fhir-api:0.1.38
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - JAVA_OPTIONS=-Xmx4096m -Xms1024m
      - BASE_URL=http://localhost:8080/baseDstu3
      - CONNECTION_STRING=jdbc:postgresql://postgres:5432/fhir?user=dev&password=leaving-grants-groups-ratio-colombia-ieee-firing-appears-finding-listings-fixed-dramatic
volumes:
  postgres-data:
